version: "3"

services:
  telzir_ui:
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - "3000:3000"
    command: yarn start
    env_file:
      - .env
    tty: true
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
